import { useEffect, useState } from 'react';
import { request } from './bridge.js';
import './local.css';

const euro = (value) => new Intl.NumberFormat('fr-FR', { style: 'currency', currency: 'EUR' }).format(value || 0);
async function api(path, payload) { return (await request(path, payload === undefined ? {} : { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(payload) })).json(); }
const newProject = () => ({ label: '', kind: 'projet', amount_eur: '', due_on: '', funding_item_id: '' });

export default function Cap({ storage, openCatalog }) {
  const [data, setData] = useState(null);
  const [message, setMessage] = useState('');
  const [project, setProject] = useState(newProject);
  const [settings, setSettings] = useState({ monthly_eur: 0, chosen_deposit_eur: 0, horizon_years: '', risk: 'non_precise' });
  const [account, setAccount] = useState({ label: '', holder: '', envelope: '' });
  const [basketId, setBasketId] = useState('');
  const [targetName, setTargetName] = useState('');
  async function refresh() {
    const result = await api('/api/budget');
    setData(result); setSettings({ monthly_eur: result.settings.monthly_eur, chosen_deposit_eur: result.settings.chosen_deposit_eur, horizon_years: result.settings.horizon_years || '', risk: result.settings.risk });
  }
  useEffect(() => { refresh().catch((error) => setMessage(error.message)); }, []);
  async function action(work) { setMessage(''); try { await work(); } catch (error) { setMessage(error.message); } }
  let workspace = null;
  try { workspace = JSON.parse(storage.getItem('champ-libre.workspace.v1') || 'null'); } catch { /* leave basket list empty */ }
  const baskets = workspace?.baskets || [];
  const selected = baskets.find((entry) => entry.id === basketId);
  const active = data?.targets.find((entry) => entry.active);
  return <main className="local-page"><header><span className="local-eyebrow">MON CAP</span><h1>Budget et cible</h1><p>Choisissez les fonds mobilisables et préservez vos projets. L’horizon et le risque sont déclarés ; ils ne produisent pas une recommandation automatique.</p></header>
    {message && <p role="status" className="local-notice">{message}</p>}
    {!data && <p>Chargement du budget…</p>}
    {data && <>
      <div className="local-metrics"><article><span>Patrimoine net</span><strong>{euro(data.snapshot.net_eur)}</strong></article><article><span>Patrimoine financier identifié</span><strong>{euro(data.financial_eur)}</strong><small>Postes non classés : {euro(data.unknown_eur)}</small></article><article><span>Liquidités mobilisables</span><strong>{euro(data.max_oneoff_eur)}</strong><small>Après réserves affectées</small></article></div>
      <section className="local-panel"><h2>Comptes et enveloppes</h2><p>Le titulaire d’un compte est distinct de la propriété patrimoniale du poste. Associez ensuite les postes au compte dans la Vue d’ensemble.</p>{!!data.accounts.length && <ul>{data.accounts.map((entry) => <li key={entry.id}>{entry.label} · {entry.envelope} · titulaire {entry.holder}</li>)}</ul>}<div className="local-form"><label>Compte<input value={account.label} onChange={(event) => setAccount({ ...account, label: event.target.value })}/></label><label>Titulaire<input value={account.holder} onChange={(event) => setAccount({ ...account, holder: event.target.value })}/></label><label>Enveloppe<input value={account.envelope} onChange={(event) => setAccount({ ...account, envelope: event.target.value })}/></label></div><p><button type="button" onClick={() => action(async () => { await api('/api/account', account); setAccount({ label: '', holder: '', envelope: '' }); await refresh(); setMessage('Compte créé.'); })}>Ajouter un compte</button></p></section>
      <section className="local-panel"><h2>Sources de financement</h2><p>Seuls les actifs classés explicitement en liquidités, actuels et dans le foyer apparaissent ici. Sélectionner un poste confirme qu’il peut financer ce PEA. Les postes réservés restent indisponibles.</p>{!data.sources.length && <p className="local-empty">Aucune liquidité classée. Classez les postes dans la Vue d’ensemble.</p>}<ul className="local-source-list">{data.sources.map((source) => <li key={source.item.id}><label><input type="checkbox" checked={source.selected} onChange={(event) => action(async () => { await api('/api/funding', { item_id: source.item.id, selected: event.target.checked }); await refresh(); })}/><strong>{source.item.label}</strong> · {source.item.owner} · valeur {euro(source.item.value_eur)}</label><span>Réserves affectées {euro(source.reserved_eur)} · mobilisable {euro(source.available_eur)}{!source.eligible && ' · poste réservé'}{source.over_reserved && ' · réserve supérieure au solde'}</span></li>)}</ul></section>
      <section className="local-panel"><h2>Projets et réserves</h2><p>Une somme ne réduit le budget que si elle est affectée à une source précise ; elle n’est soustraite qu’une fois de cette source.</p>{!!data.projects.length && <ul>{data.projects.map((entry) => <li key={entry.id}>{entry.label} · {euro(entry.amount_eur)} · {entry.due_on || 'sans échéance'} · {data.sources.find((source) => source.item.id === entry.funding_item_id)?.item.label || 'source à affecter'} <button type="button" onClick={() => setProject({ id: entry.id, label: entry.label, kind: entry.kind, amount_eur: entry.amount_eur, due_on: entry.due_on || '', funding_item_id: entry.funding_item_id || '' })}>Modifier</button></li>)}</ul>}<div className="local-form"><label>Projet ou réserve<input value={project.label} onChange={(event) => setProject({ ...project, label: event.target.value })}/></label><label>Nature<select value={project.kind} onChange={(event) => setProject({ ...project, kind: event.target.value })}><option value="projet">Projet</option><option value="reserve">Réserve</option></select></label><label>Montant à préserver (€)<input type="number" min="0" step="0.01" value={project.amount_eur} onChange={(event) => setProject({ ...project, amount_eur: event.target.value })}/></label><label>Échéance<input type="date" value={project.due_on} onChange={(event) => setProject({ ...project, due_on: event.target.value })}/></label><label>Source à préserver<select value={project.funding_item_id} onChange={(event) => setProject({ ...project, funding_item_id: event.target.value })}><option value="">Non affectée</option>{data.sources.map((source) => <option key={source.item.id} value={source.item.id}>{source.item.label}</option>)}</select></label></div><p><button type="button" onClick={() => action(async () => { await api('/api/project', project); setProject(newProject()); await refresh(); setMessage('Projet ou réserve enregistré.'); })}>Enregistrer ce projet</button></p></section>
      <section className="local-panel"><h2>Budget déclaré</h2><p>La capacité mensuelle est future et n’est pas ajoutée aux espèces actuelles. Le versement ponctuel doit rester dans la limite des liquidités mobilisables.</p><div className="local-form"><label>Capacité mensuelle (€)<input type="number" min="0" step="0.01" value={settings.monthly_eur} onChange={(event) => setSettings({ ...settings, monthly_eur: event.target.value })}/></label><label>Versement ponctuel retenu (€)<input type="number" min="0" max={data.max_oneoff_eur} step="0.01" value={settings.chosen_deposit_eur} onChange={(event) => setSettings({ ...settings, chosen_deposit_eur: event.target.value })}/></label><label>Horizon (années)<input type="number" min="1" max="60" value={settings.horizon_years} onChange={(event) => setSettings({ ...settings, horizon_years: event.target.value })}/></label><label>Risque déclaré<select value={settings.risk} onChange={(event) => setSettings({ ...settings, risk: event.target.value })}><option value="non_precise">Non précisé</option><option value="prudent">Prudent</option><option value="equilibre">Équilibré</option><option value="dynamique">Dynamique</option></select></label></div><p><button type="button" onClick={() => action(async () => { await api('/api/budget-settings', settings); await refresh(); setMessage('Budget enregistré sans modifier les avoirs.'); })}>Enregistrer le budget</button></p></section>
      <section className="local-panel"><h2>Cible active</h2>{active ? <p><strong>{active.name}</strong> · version {active.version} · {Object.entries(active.weights).map(([isin, weight]) => `${isin} ${weight} %`).join(' · ')}</p> : <p className="local-empty">Aucune cible active. Construisez ou enregistrez un panier, puis activez-en une copie ici.</p>}<p><button type="button" onClick={openCatalog}>Ouvrir le constructeur ETF</button></p><div className="local-form"><label>Panier enregistré<select value={basketId} onChange={(event) => { setBasketId(event.target.value); setTargetName(baskets.find((entry) => entry.id === event.target.value)?.name || ''); }}><option value="">Choisir…</option>{baskets.map((entry) => <option key={entry.id} value={entry.id}>{entry.name}</option>)}</select></label><label>Nom de la cible<input value={targetName} onChange={(event) => setTargetName(event.target.value)}/></label></div><p><button type="button" disabled={!selected} onClick={() => action(async () => { await api('/api/target', { name: targetName, weights: selected.snapshot.weights, source: `panier ${selected.id}` }); await refresh(); setMessage('Copie versionnée activée. Le panier reste indépendant.'); })}>Activer une copie de ce panier</button></p></section>
    </>}
  </main>;
}
